# Local dependencies (optional Docker)

services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - heybrew_mongo:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  heybrew_mongo:
