/**
 * Official HeyBrew menu — prices in PKR (converted to paisa in seed).
 * Duplicate names across categories get unique slugs with a category prefix.
 */

export type OfficialProduct = {
  name: string;
  slug: string;
  description: string;
  categorySlug: string;
  priceRs: number;
  featured?: boolean;
  keywords?: string[];
};

export const OFFICIAL_CATEGORIES = [
  { name: "Popular", slug: "popular", displayOrder: 1 },
  { name: "Hot Brew", slug: "hot-brew", displayOrder: 2 },
  { name: "Specialty", slug: "specialty", displayOrder: 3 },
  { name: "Cold Brew", slug: "cold-brew", displayOrder: 4 },
  { name: "Matcha", slug: "matcha", displayOrder: 5 },
  { name: "Frappe", slug: "frappe", displayOrder: 6 },
  { name: "Mojitos / Refreshers", slug: "mojitos-refreshers", displayOrder: 7 },
  { name: "Shakes", slug: "shakes", displayOrder: 8 },
  { name: "Juice", slug: "juice", displayOrder: 9 },
  { name: "Beverages", slug: "beverages", displayOrder: 10 },
  { name: "Add Ons", slug: "add-ons", displayOrder: 11 },
  { name: "The Bites", slug: "the-bites", displayOrder: 12 },
] as const;

export const OFFICIAL_PRODUCTS: OfficialProduct[] = [
  // ——— Hot Brew ———
  {
    name: "Espresso",
    slug: "espresso",
    description: "A bold and concentrated coffee with a rich, intense finish.",
    categorySlug: "hot-brew",
    priceRs: 350,
    featured: true,
    keywords: ["hot", "espresso", "coffee"],
  },
  {
    name: "Americano",
    slug: "americano",
    description: "Smooth espresso blended with hot water for a clean, bold taste.",
    categorySlug: "hot-brew",
    priceRs: 400,
    keywords: ["hot", "americano", "coffee"],
  },
  {
    name: "Cappuccino",
    slug: "cappuccino",
    description: "Rich espresso topped with creamy milk and soft foam.",
    categorySlug: "hot-brew",
    priceRs: 500,
    featured: true,
    keywords: ["hot", "cappuccino", "coffee"],
  },
  {
    name: "Latte",
    slug: "hot-latte",
    description: "Smooth espresso with steamed milk for a creamy, balanced sip.",
    categorySlug: "hot-brew",
    priceRs: 600,
    keywords: ["hot", "latte", "coffee"],
  },
  {
    name: "Caramel Latte",
    slug: "caramel-latte",
    description: "Creamy coffee with a sweet and buttery caramel touch.",
    categorySlug: "hot-brew",
    priceRs: 700,
    keywords: ["hot", "caramel", "latte"],
  },
  {
    name: "French Vanilla Latte",
    slug: "hot-french-vanilla-latte",
    description: "Smooth espresso with creamy milk and sweet vanilla flavor.",
    categorySlug: "hot-brew",
    priceRs: 750,
    keywords: ["hot", "vanilla", "latte"],
  },
  {
    name: "Hazelnut Latte",
    slug: "hot-hazelnut-latte",
    description: "A warm and creamy latte with rich roasted hazelnut notes.",
    categorySlug: "hot-brew",
    priceRs: 700,
    keywords: ["hot", "hazelnut", "latte"],
  },
  {
    name: "Spanish Latte",
    slug: "spanish-latte",
    description: "Sweet, creamy and smooth coffee with a rich milky finish.",
    categorySlug: "hot-brew",
    priceRs: 700,
    featured: true,
    keywords: ["hot", "spanish", "latte", "popular"],
  },
  {
    name: "Marshmallow Latte",
    slug: "hot-marshmallow-latte",
    description: "A creamy latte with soft and sweet marshmallow flavor.",
    categorySlug: "hot-brew",
    priceRs: 700,
    keywords: ["hot", "marshmallow", "latte"],
  },
  {
    name: "Pistachio Latte",
    slug: "hot-pistachio-latte",
    description: "Rich espresso blended with creamy and nutty pistachio flavor.",
    categorySlug: "hot-brew",
    priceRs: 800,
    keywords: ["hot", "pistachio", "latte"],
  },
  {
    name: "White Chocolate Latte",
    slug: "hot-white-chocolate-latte",
    description: "Creamy espresso with smooth and sweet white chocolate flavor.",
    categorySlug: "hot-brew",
    priceRs: 700,
    keywords: ["hot", "white chocolate", "latte"],
  },
  {
    name: "Mocha Latte",
    slug: "hot-mocha-latte",
    description: "A rich combination of coffee, milk and smooth chocolate.",
    categorySlug: "hot-brew",
    priceRs: 700,
    keywords: ["hot", "mocha", "latte"],
  },
  {
    name: "Hot Chocolate",
    slug: "hot-chocolate",
    description: "Rich and creamy chocolate served warm for a comforting treat.",
    categorySlug: "hot-brew",
    priceRs: 600,
    keywords: ["hot", "chocolate"],
  },
  {
    name: "Affogato + Flat White",
    slug: "affogato-flat-white",
    description:
      "A rich coffee experience with smooth espresso and creamy texture.",
    categorySlug: "hot-brew",
    priceRs: 450,
    keywords: ["hot", "affogato", "flat white"],
  },
  {
    name: "Cortado",
    slug: "cortado",
    description: "Strong espresso balanced with a small amount of warm milk.",
    categorySlug: "hot-brew",
    priceRs: 450,
    keywords: ["hot", "cortado", "espresso"],
  },

  // ——— Specialty ———
  {
    name: "V60",
    slug: "v60",
    description:
      "Freshly brewed pour over coffee with a clean and aromatic taste.",
    categorySlug: "specialty",
    priceRs: 600,
    featured: true,
    keywords: ["specialty", "v60", "pour over"],
  },

  // ——— Cold Brew ———
  {
    name: "Latte",
    slug: "cold-latte",
    description: "Smooth chilled coffee blended with creamy milk.",
    categorySlug: "cold-brew",
    priceRs: 750,
    keywords: ["cold", "latte"],
  },
  {
    name: "Salted Caramel Latte",
    slug: "salted-caramel-latte",
    description:
      "Creamy iced coffee with sweet caramel and a subtle salty touch.",
    categorySlug: "cold-brew",
    priceRs: 750,
    keywords: ["cold", "caramel", "salted"],
  },
  {
    name: "French Vanilla Latte",
    slug: "cold-french-vanilla-latte",
    description: "Chilled creamy coffee with sweet and aromatic vanilla flavor.",
    categorySlug: "cold-brew",
    priceRs: 800,
    keywords: ["cold", "vanilla", "latte"],
  },
  {
    name: "Hazelnut Latte",
    slug: "cold-hazelnut-latte",
    description: "Smooth iced latte with rich and nutty hazelnut notes.",
    categorySlug: "cold-brew",
    priceRs: 750,
    keywords: ["cold", "hazelnut", "latte"],
  },
  {
    name: "Spanish Latte",
    slug: "cold-spanish-latte",
    description: "Sweet and creamy chilled coffee with a rich milky finish.",
    categorySlug: "cold-brew",
    priceRs: 750,
    featured: true,
    keywords: ["cold", "spanish", "latte", "popular"],
  },
  {
    name: "Marshmallow Latte",
    slug: "cold-marshmallow-latte",
    description: "Creamy iced coffee with a soft and sweet marshmallow flavor.",
    categorySlug: "cold-brew",
    priceRs: 750,
    keywords: ["cold", "marshmallow", "latte"],
  },
  {
    name: "Pistachio Latte",
    slug: "cold-pistachio-latte",
    description: "Smooth chilled latte with rich and creamy pistachio flavor.",
    categorySlug: "cold-brew",
    priceRs: 800,
    keywords: ["cold", "pistachio", "latte"],
  },
  {
    name: "White Chocolate Latte",
    slug: "cold-white-chocolate-latte",
    description: "Creamy iced coffee with smooth white chocolate sweetness.",
    categorySlug: "cold-brew",
    priceRs: 750,
    keywords: ["cold", "white chocolate", "latte"],
  },
  {
    name: "Mocha Latte",
    slug: "cold-mocha-latte",
    description: "Rich chocolate and coffee blended into a smooth chilled drink.",
    categorySlug: "cold-brew",
    priceRs: 750,
    keywords: ["cold", "mocha", "latte"],
  },

  // ——— Matcha ———
  {
    name: "Matcha Green",
    slug: "matcha-green",
    description:
      "Smooth and earthy matcha blended into a refreshing creamy drink.",
    categorySlug: "matcha",
    priceRs: 750,
    keywords: ["matcha", "green"],
  },
  {
    name: "Strawberry Matcha",
    slug: "strawberry-matcha",
    description: "Earthy matcha paired with sweet and fruity strawberry flavor.",
    categorySlug: "matcha",
    priceRs: 850,
    featured: true,
    keywords: ["matcha", "strawberry", "popular"],
  },
  {
    name: "Mango Matcha",
    slug: "mango-matcha",
    description: "Smooth matcha blended with the tropical sweetness of mango.",
    categorySlug: "matcha",
    priceRs: 850,
    keywords: ["matcha", "mango"],
  },

  // ——— Frappe ———
  {
    name: "Vanilla Frappe",
    slug: "vanilla-frappe",
    description: "A creamy blended drink with smooth and sweet vanilla flavor.",
    categorySlug: "frappe",
    priceRs: 850,
    keywords: ["frappe", "vanilla"],
  },
  {
    name: "Caramel Frappe",
    slug: "caramel-frappe",
    description: "Rich and creamy frappe blended with sweet caramel goodness.",
    categorySlug: "frappe",
    priceRs: 850,
    keywords: ["frappe", "caramel"],
  },
  {
    name: "Hazelnut Frappe",
    slug: "hazelnut-frappe",
    description: "A chilled creamy blend with rich roasted hazelnut flavor.",
    categorySlug: "frappe",
    priceRs: 850,
    keywords: ["frappe", "hazelnut"],
  },
  {
    name: "Mocha Frappe",
    slug: "mocha-frappe",
    description:
      "A refreshing blend of coffee and chocolate with a creamy finish.",
    categorySlug: "frappe",
    priceRs: 850,
    keywords: ["frappe", "mocha"],
  },
  {
    name: "Lotus Frappe",
    slug: "lotus-frappe",
    description: "A creamy frappe packed with rich Lotus biscuit flavor.",
    categorySlug: "frappe",
    priceRs: 900,
    keywords: ["frappe", "lotus"],
  },
  {
    name: "Pistachio Frappe",
    slug: "pistachio-frappe",
    description: "A smooth and creamy frappe with rich pistachio flavor.",
    categorySlug: "frappe",
    priceRs: 950,
    featured: true,
    keywords: ["frappe", "pistachio", "popular"],
  },
  {
    name: "Tiramisu Frappe",
    slug: "tiramisu-frappe",
    description:
      "A creamy coffee blend inspired by the classic tiramisu dessert.",
    categorySlug: "frappe",
    priceRs: 950,
    keywords: ["frappe", "tiramisu"],
  },
  {
    name: "Marshmallow Frappe",
    slug: "marshmallow-frappe",
    description: "A sweet and creamy blended drink with marshmallow goodness.",
    categorySlug: "frappe",
    priceRs: 850,
    keywords: ["frappe", "marshmallow"],
  },

  // ——— Mojitos / Refreshers ———
  {
    name: "Bull Hit",
    slug: "bull-hit",
    description: "A bold and energizing refresher with a crisp, chilled finish.",
    categorySlug: "mojitos-refreshers",
    priceRs: 900,
    featured: true,
    keywords: ["mojito", "refresher", "bull hit", "popular"],
  },
  {
    name: "Blue Lagoon",
    slug: "blue-lagoon",
    description: "A bright and refreshing drink with a cool fruity taste.",
    categorySlug: "mojitos-refreshers",
    priceRs: 750,
    keywords: ["mojito", "blue lagoon"],
  },
  {
    name: "Strawberry Mojito",
    slug: "strawberry-mojito",
    description: "Sweet strawberry flavor with a refreshing and fizzy finish.",
    categorySlug: "mojitos-refreshers",
    priceRs: 750,
    keywords: ["mojito", "strawberry"],
  },
  {
    name: "Blue Berry",
    slug: "blue-berry",
    description: "A refreshing fruity drink packed with sweet blueberry flavor.",
    categorySlug: "mojitos-refreshers",
    priceRs: 750,
    keywords: ["mojito", "blueberry"],
  },
  {
    name: "Passion Fruit",
    slug: "passion-fruit",
    description:
      "A tropical refresher with a sweet and tangy passion fruit taste.",
    categorySlug: "mojitos-refreshers",
    priceRs: 750,
    keywords: ["mojito", "passion fruit"],
  },
  {
    name: "Lemonade",
    slug: "lemonade",
    description: "Fresh and citrusy lemonade with a cool refreshing finish.",
    categorySlug: "mojitos-refreshers",
    priceRs: 500,
    keywords: ["lemonade", "refresher"],
  },
  {
    name: "Mint Lemonade",
    slug: "mint-lemonade",
    description:
      "Refreshing lemonade blended with fresh and cooling mint flavor.",
    categorySlug: "mojitos-refreshers",
    priceRs: 600,
    keywords: ["lemonade", "mint"],
  },

  // ——— Shakes ———
  {
    name: "Banana Shake",
    slug: "banana-shake",
    description: "A smooth and creamy shake made with sweet banana flavor.",
    categorySlug: "shakes",
    priceRs: 400,
    keywords: ["shake", "banana"],
  },
  {
    name: "Power Banana",
    slug: "power-banana",
    description:
      "A rich banana shake made for a more filling and energizing sip.",
    categorySlug: "shakes",
    priceRs: 550,
    keywords: ["shake", "banana", "power"],
  },
  {
    name: "Nutty Banana",
    slug: "nutty-banana",
    description: "Creamy banana blended with rich and delicious nutty flavors.",
    categorySlug: "shakes",
    priceRs: 700,
    keywords: ["shake", "banana", "nutty"],
  },
  {
    name: "Mango Shake (Seasonal)",
    slug: "mango-shake",
    description: "A thick and creamy shake packed with sweet mango flavor.",
    categorySlug: "shakes",
    priceRs: 550,
    keywords: ["shake", "mango", "seasonal"],
  },
  {
    name: "Mix Fusion",
    slug: "mix-fusion",
    description: "A refreshing creamy blend of delicious mixed flavors.",
    categorySlug: "shakes",
    priceRs: 600,
    keywords: ["shake", "mix", "fusion"],
  },
  {
    name: "Strawberry (Seasonal)",
    slug: "strawberry-shake",
    description: "A smooth and creamy shake with sweet strawberry flavor.",
    categorySlug: "shakes",
    priceRs: 600,
    keywords: ["shake", "strawberry", "seasonal"],
  },
  {
    name: "Protein Shake",
    slug: "protein-shake",
    description: "A rich and satisfying shake packed with protein and flavor.",
    categorySlug: "shakes",
    priceRs: 1100,
    featured: true,
    keywords: ["shake", "protein", "popular"],
  },

  // ——— Juice ———
  {
    name: "Apple Juice",
    slug: "apple-juice",
    description: "Fresh and refreshing apple flavor with a naturally sweet taste.",
    categorySlug: "juice",
    priceRs: 450,
    keywords: ["juice", "apple"],
  },
  {
    name: "A.B.C",
    slug: "abc-juice",
    description: "A refreshing blend of apple, beetroot and carrot goodness.",
    categorySlug: "juice",
    priceRs: 550,
    keywords: ["juice", "abc", "apple", "beetroot", "carrot"],
  },
  {
    name: "Immunizer",
    slug: "immunizer",
    description: "A refreshing juice blend crafted for a fresh and uplifting sip.",
    categorySlug: "juice",
    priceRs: 500,
    keywords: ["juice", "immunizer"],
  },
  {
    name: "Health Booster",
    slug: "health-booster",
    description:
      "A vibrant juice blend made for a refreshing and wholesome drink.",
    categorySlug: "juice",
    priceRs: 600,
    keywords: ["juice", "health"],
  },
  {
    name: "Liver Purifier",
    slug: "liver-purifier",
    description: "A fresh and refreshing juice blend with clean natural flavors.",
    categorySlug: "juice",
    priceRs: 600,
    featured: true,
    keywords: ["juice", "liver", "popular"],
  },
  {
    name: "Immuno Hit",
    slug: "immuno-hit",
    description: "A refreshing blend with bright flavors for an energizing sip.",
    categorySlug: "juice",
    priceRs: 600,
    keywords: ["juice", "immuno"],
  },
  {
    name: "Peach & Apple",
    slug: "peach-apple",
    description: "Sweet peach and crisp apple blended into a refreshing drink.",
    categorySlug: "juice",
    priceRs: 550,
    keywords: ["juice", "peach", "apple"],
  },

  // ——— Beverages ———
  {
    name: "Cold Drinks",
    slug: "cold-drinks",
    description: "A chilled fizzy beverage for a quick and refreshing sip.",
    categorySlug: "beverages",
    priceRs: 150,
    keywords: ["beverage", "cold drink", "soda"],
  },
  {
    name: "RedBull",
    slug: "redbull",
    description: "A chilled energy drink for a refreshing boost.",
    categorySlug: "beverages",
    priceRs: 700,
    keywords: ["beverage", "redbull", "energy"],
  },
  {
    name: "Water",
    slug: "water",
    description: "Chilled bottled water to keep you refreshed.",
    categorySlug: "beverages",
    priceRs: 100,
    keywords: ["beverage", "water"],
  },

  // ——— Add Ons ———
  {
    name: "Extra Shot",
    slug: "extra-shot",
    description: "Add an extra espresso shot for a stronger coffee kick.",
    categorySlug: "add-ons",
    priceRs: 350,
    keywords: ["addon", "espresso", "shot"],
  },
  {
    name: "Extra Syrup",
    slug: "extra-syrup",
    description: "Add your favorite syrup for extra sweetness and flavor.",
    categorySlug: "add-ons",
    priceRs: 150,
    keywords: ["addon", "syrup"],
  },
  {
    name: "Whipped Cream",
    slug: "whipped-cream",
    description: "Add a smooth and creamy whipped topping to your drink.",
    categorySlug: "add-ons",
    priceRs: 150,
    keywords: ["addon", "whipped cream"],
  },
  {
    name: "Ice Cream",
    slug: "ice-cream-addon",
    description: "Add a creamy scoop for an extra indulgent touch.",
    categorySlug: "add-ons",
    priceRs: 200,
    keywords: ["addon", "ice cream"],
  },

  // ——— The Bites ———
  {
    name: "Lotus Brownie",
    slug: "lotus-brownie",
    description: "Fudgy chocolate brownie topped with rich Lotus spread.",
    categorySlug: "the-bites",
    priceRs: 400,
    featured: true,
    keywords: ["bites", "brownie", "lotus", "dessert", "popular"],
  },
  {
    name: "Chocolate Chunks Brownie",
    slug: "chocolate-chunks-brownie",
    description:
      "Rich and fudgy brownie loaded with delicious chocolate chunks.",
    categorySlug: "the-bites",
    priceRs: 400,
    keywords: ["bites", "brownie", "chocolate"],
  },
  {
    name: "Nutella Brownie",
    slug: "nutella-brownie",
    description: "A soft fudgy brownie filled with rich Nutella goodness.",
    categorySlug: "the-bites",
    priceRs: 400,
    keywords: ["bites", "brownie", "nutella"],
  },
  {
    name: "Fudge Brownie",
    slug: "fudge-brownie",
    description: "Rich, gooey and chocolatey brownie with a fudgy center.",
    categorySlug: "the-bites",
    priceRs: 350,
    keywords: ["bites", "brownie", "fudge"],
  },
  {
    name: "Oreo Cheesecake",
    slug: "oreo-cheesecake",
    description: "Creamy cheesecake packed with delicious Oreo flavor.",
    categorySlug: "the-bites",
    priceRs: 600,
    keywords: ["bites", "cheesecake", "oreo"],
  },
  {
    name: "Lotus Cheesecake",
    slug: "lotus-cheesecake",
    description: "Smooth and creamy cheesecake with rich Lotus biscuit flavor.",
    categorySlug: "the-bites",
    priceRs: 700,
    keywords: ["bites", "cheesecake", "lotus"],
  },
  {
    name: "Caramel Three Milk Cake",
    slug: "caramel-three-milk-cake",
    description: "Soft and moist milk cake finished with sweet caramel flavor.",
    categorySlug: "the-bites",
    priceRs: 550,
    keywords: ["bites", "cake", "caramel", "tres leches"],
  },
  {
    name: "Oreo Three Milk Cake",
    slug: "oreo-three-milk-cake",
    description: "Soft and creamy milk cake with rich Oreo goodness.",
    categorySlug: "the-bites",
    priceRs: 550,
    keywords: ["bites", "cake", "oreo", "tres leches"],
  },
  {
    name: "Lotus Three Milk Cake",
    slug: "lotus-three-milk-cake",
    description: "Moist and creamy milk cake packed with Lotus flavor.",
    categorySlug: "the-bites",
    priceRs: 600,
    keywords: ["bites", "cake", "lotus", "tres leches"],
  },
  {
    name: "Centre Filled Cookies",
    slug: "centre-filled-cookies",
    description: "Soft baked cookies with a rich and delicious filled center.",
    categorySlug: "the-bites",
    priceRs: 200,
    keywords: ["bites", "cookies"],
  },
];
